services:
  speed-object-detection-camera:
    build: .
    container_name: speed-object-detection-camera
    ports:
      - "5000:5000"
    volumes:
      - config_data:/configdata
      - detections_data:/app/detections
      - models_data:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "
        [ ! -f /configdata/config.json ] && cp /defaults/config.json /configdata/config.json || true &&
        cp /configdata/config.json /app/config.json &&
        [ -z \"$(ls -A /app/models 2>/dev/null)\" ] && cp -r /defaults/models/* /app/models/ || true &&
        [ -z \"$(ls -A /app/detections 2>/dev/null)\" ] && cp -r /defaults/detections/* /app/detections/ || true &&
        python app.py
      "

volumes:
  config_data:
  detections_data:
  models_data:
