services:
  speed-object-detection-camera:
    build: .
    container_name: speed-object-detection-camera
    ports:
      - "5000:5000"
    volumes:
      - config_data:/configdata
      - detections_data:/app/detections
      - models_data:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "
        [ ! -f /configdata/config.json ] && cp /app/config.json /configdata/config.json || true &&
        cp /configdata/config.json /app/config.json &&
        python speed_camera_web.py
      "

volumes:
  config_data:
  detections_data:
  models_data:
