services:
  speed-object-detection-camera:
    build: .
    container_name: speed-object-detection-camera
    ports:
      - "5000:5000"
    volumes:
      - detections_data:/app/detections
      - models_data:/app/models
      - config_data:/app/config.json
    environment:
      - PYTHONUNBUFFERED=1
    command: sh /app/entrypoint.sh
    restart: unless-stopped

volumes:
  detections_data:
  models_data:
  config_data:
